GET http://localhost:5000/api/testimonials

###

GET http://localhost:5000/api/testimonials/2

###

POST http://localhost:5000/api/testimonials/
Content-Type: application/json

{
    "name":"Jeremia",
    "status": 1,
    "is_deleted": 1 
}

###

PUT http://localhost:5000/api/testimonials/6
Content-Type: application/json

{
    "name":"Jeremia Ganteng",
    "status": 1,
    "is_deleted": 1 
}

###

DELETE http://localhost:5000/api/testimonials/5
Content-Type: application/json

{
   
}

###
