GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/2

###

POST http://localhost:5000/api/users/
Content-Type: application/json

{   
    "firstname":"Jeremia",
    "lastname": "Narmo",
    "email": "Naraj@gmail.com",
    "placeofbirth": "Jakarta",
    "birthdate": "2000-09-04T17:00:00.000Z",
    "country": "Indonesia",
    "current_location": "Jakarta",
    "timezone": 12,
    "phone": "9874563210",
    "status": "Active"   
}

###

PUT http://localhost:5000/api/users/22
Content-Type: application/json

{
    "firstname":"Jeremia",
    "lastname": "Narmo2",
    "email": "jere@gmail.com",
    "placeofbirth": "Jakarta2",
    "birthdate": "2010-09-04T17:00:00.000Z",
    "country": "Indonesia2",
    "current_location": "Serang2",
    "timezone": 12,
    "phone": "0851348814",
    "status": "Active"   
}

###

DELETE http://localhost:5000/api/users/3
Content-Type: application/json

{
   
}

###
