GET http://localhost:5000/api/auth

###

GET http://localhost:5000/api/auth/2

###

POST http://localhost:5000/api/auth/
Content-Type: application/json

{   
    "name":"Jeremia2",
    "email": "maratik@gmail.com",
    "password": "Jeremia2",
    "confPassword": "Jeremia2"     
}

###

PUT http://localhost:5000/api/auth/22
Content-Type: application/json

{
    "firstname":"Jeremia",
    "lastname": "Narmo2",
    "email": "jere@gmail.com",
    "placeofbirth": "Jakarta2",
    "birthdate": "2010-09-04T17:00:00.000Z",
    "country": "Indonesia2",
    "current_location": "Serang2",
    "timezone": 12,
    "phone": "0851348814",
    "status": "Active"   
}

###

DELETE http://localhost:5000/api/auth/11
Content-Type: application/json

{
   
}

###
