GET http://localhost:5000/api/employees

###

GET http://localhost:5000/api/employees/2

###

POST http://localhost:5000/api/employees/
Content-Type: application/json

{
            "nik": "9106120910000002",
            "name": "MARATIK JEREMIA KLUIFER NARMO",
            "place_birth": "Biak",
            "date_birth": "2000-10-09T17:00:00.000Z",
            "email": "maratikjknarmo@gmail.com",
            "gender": "LAKI-LAKI",
            "blood_type": "A",
            "address": "LINGK.PERSADA BANTEN BLOK AA NO 03",
            "rt": "007",
            "rw": "003",
            "village": "KAPUREN",
            "districts": "WALANTAKA",
            "religion": "KRISTEN PROTESTAN",
            "marital": "BELUM KAWIN",
            "occupation": "MAHASISWA",
            "citizen": "WNI",
            "phone_number": "9874563210",
            "status": "ACTIVE"
}

###

PUT http://localhost:5000/api/employees/12
Content-Type: application/json

{
            "nik": "9106120910000002",
            "name": "MICHAEL NARMO2",
            "place_birth": "Biak2",
            "date_birth": "2002-11-25T17:00:00.000Z",
            "email": "maratikjknarmo@gmail.com",
            "gender": "LAKI-LAKI",
            "blood_type": "O",
            "address": "LINGK.PERSADA BANTEN BLOK AA NO 03",
            "rt": "007",
            "rw": "003",
            "village": "KAPUREN",
            "districts": "WALANTAKA",
            "religion": "KRISTEN PROTESTAN",
            "marital": "BELUM KAWIN",
            "occupation": "MAHASISWA",
            "citizen": "WNI",
            "phone_number": "9874563210",
            "status": "ACTIVE" 
}

###

DELETE http://localhost:5000/api/employees/15
Content-Type: application/json

{
   
}

###

###
