GET http://localhost:5000/api/temp_consult123456

###

GET http://localhost:5000/api/temp_consult/2

###

POST http://localhost:5000/api/temp_consult/
Content-Type: application/json

{   
    "userid":"999893",
    "no_transaction": "110421",
    "PIC": "Budi Sentosa",
    "transactiondate": "2000-09-04T17:00:00.000Z"
}

###

PUT http://localhost:5000/api/temp_consult/22
Content-Type: application/json

{
    "firstname":"Jeremia",
    "lastname": "Narmo2",
    "email": "jere@gmail.com",
    "placeofbirth": "Jakarta2",
    "birthdate": "2010-09-04T17:00:00.000Z",
    "country": "Indonesia2",
    "current_location": "Serang2",
    "timezone": 12,
    "phone": "0851348814",
    "status": "Active"   
}

###

DELETE http://localhost:5000/api/temp_consult/3
Content-Type: application/json

{
   
}

###
